name: site
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: Sanjay <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  bootstrap: ^3.3.7
  js: ^0.6.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  json_object: ^1.0.19

transformers:
- dart_to_js_script_rewriter
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.3.7
# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
